In [8]:
# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

#code >
import numpy as np
arr = np.arange(6)
print('Data type:', arr.dtype)

# example
print(arr)

Data type: int64
[0 1 2 3 4 5]


In [ ]:
# 2. Given a NumPy array 'arr', check if its data type is float64.
# arr = np.array([1.5, 2.6, 3.7])

#code >
import numpy as np
arr = np.array([1.5, 2.6, 3.7])
print('Is data type float64?', arr.dtype == np.float64)

#example >
print(arr)

Is data type float64? True
[1.5 2.6 3.7]


In [11]:
# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

#code >
import numpy as np
arr = np.array([2+3j, 4+5j, 6+7j], dtype=np.complex128)
print('Data type:', arr.dtype)

#example >
print(arr)

Data type: complex128
[2.+3.j 4.+5.j 6.+7.j]


In [12]:
# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.

#code >
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype(np.float32)
print('Data type:', arr.dtype)

#example >
print(arr)

Data type: float32
[1. 2. 3. 4. 5.]


In [13]:
# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

#code >
arr = np.array([1.123456789, 2.987654321], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print('Converted dtype:', arr_float32.dtype)

# example
print(arr_float32)

Converted dtype: float32
[1.1234568 2.9876542]


In [14]:
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

#code >
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

# example
arr = np.array([[1, 2], [3, 4]])
print(array_attributes(arr))

((2, 2), 4, dtype('int64'))


In [15]:
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

#code >
def array_dimension(arr):
    return arr.ndim

# example
arr = np.array([[1, 2], [3, 4]])
print(array_dimension(arr))

2


In [16]:
# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

#code >
def item_size_info(arr):
    return arr.itemsize, arr.nbytes

# example
arr = np.array([1, 2, 3], dtype=np.int32)
print(item_size_info(arr))

(4, 12)


In [17]:
# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

#code >
def array_strides(arr):
    return arr.strides

# example
arr = np.array([1.5, 2.6, 3.7])
print(array_strides(arr))

(8,)


In [18]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

#code >
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

# example
arr = np.array([[1, 2], [3, 4]])
print(shape_stride_relationship(arr))

((2, 2), (16, 8))


In [19]:
# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

#code >
def create_zeros_array(n):
    return np.zeros(n)

# example
print(create_zeros_array(5))

[0. 0. 0. 0. 0.]


In [20]:
# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

#code >
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

# example
print(create_ones_matrix(2, 3))

[[1. 1. 1.]
 [1. 1. 1.]]


In [21]:
# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

#code >
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

# example
print(generate_range_array(1, 10, 2))

[1 3 5 7 9]


In [22]:
# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

#code >
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

# example
print(generate_linear_space(1.0, 5.0, 5))

[1. 2. 3. 4. 5.]


In [23]:
# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

#code >
def create_identity_matrix(n):
    return np.eye(n)

# example
print(create_identity_matrix(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
# 16. Write a function that takes a Python list and converts it into a NumPy array.

#code >
def list_to_numpy_array(lst):
    return np.array(lst)

# example
print(list_to_numpy_array([1, 2, 3, 4]))

[1 2 3 4]


In [25]:
# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

#code >
arr = np.array([10, 20, 30, 40])
view_arr = arr.view()
print('Original:', arr)
print('View:', view_arr)

# example
view_arr[0] = 100
print('Modified view:', view_arr)
print('Original after modifying view:', arr)

Original: [10 20 30 40]
View: [10 20 30 40]
Modified view: [100  20  30  40]
Original after modifying view: [100  20  30  40]


In [ ]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

#code >
import numpy as np
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

# example
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(concatenate_arrays(a, b, axis=0))

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

#code >
import numpy as np
def horizontal_concatenate():
    arr1 = np.array([[1], [2]])
    arr2 = np.array([[3, 4], [5, 6]])
    return np.concatenate((arr1, arr2), axis=1)

# example
print(horizontal_concatenate())

[[1 3 4]
 [2 5 6]]


In [ ]:
# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

#code >
import numpy as np
def vertical_stack(arrays):
    return np.vstack(arrays)

# example
a = np.array([1, 2])
b = np.array([3, 4])
print(vertical_stack([a, b]))

[[1 2]
 [3 4]]


In [ ]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

#code >
import numpy as np
def create_range_array(start, stop, step):
    return np.arange(start, stop + 1, step)

# example
print(create_range_array(1, 10, 2))

[1 3 5 7 9]


In [ ]:
# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

#code >
import numpy as np
def generate_linspace():
    return np.linspace(0, 1, 10)

# example
print(generate_linspace())

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

#code >
import numpy as np
def generate_logspace():
    return np.logspace(0, 3, 5)

# example
print(generate_logspace())

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [ ]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

#code >
import numpy as np
import pandas as pd
def create_dataframe():
    data = np.random.randint(1, 101, size=(5, 3))
    return pd.DataFrame(data, columns=['A', 'B', 'C'])

# example
print(create_dataframe())

    A   B   C
0  34  94  11
1  52  60  92
2  95  64  58
3  29  59  72
4  44   7  57


In [ ]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

#code >
import pandas as pd
import numpy as np
def replace_negatives(df, column):
    df[column] = np.where(df[column] < 0, 0, df[column])
    return df

# example
df = pd.DataFrame({'A': [1, -2, 3], 'B': [-4, 5, -6]})
print(replace_negatives(df, 'A'))

   A  B
0  1 -4
1  0  5
2  3 -6


In [ ]:
# 26. Access the 3rd element from the given NumPy array.
# arr = np.array([10, 20, 30, 40, 50])

#code >
import numpy as np
def access_third_element(arr):
    return arr[2]

# example
arr = np.array([10, 20, 30, 40, 50])
print(access_third_element(arr))

30


In [ ]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.
# arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#code >
import numpy as np
def get_element_1_2(arr):
    return arr[1, 2]

# example
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(get_element_1_2(arr))

6


In [ ]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
# arr = np.array([3, 8, 2, 10, 5, 7])

#code >
import numpy as np
def extract_greater_than_5(arr):
    return arr[arr > 5]

# example
arr = np.array([3, 8, 2, 10, 5, 7])
print(extract_greater_than_5(arr))

[ 8 10  7]


In [ ]:
# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
# arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#code >
import numpy as np
def slice_array(arr):
    return arr[2:6]

# example
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(slice_array(arr))

[3 4 5 6]


In [ ]:
# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
# arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#code >
import numpy as np
def extract_sub_array(arr):
    return arr[0:2, 1:3]

# example
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(extract_sub_array(arr))

[[2 3]
 [5 6]]


In [ ]:
# 31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

#code >
import numpy as np
def extract_by_indices(arr, indices):
    return arr[tuple(indices.T)]

# example
arr = np.array([[10, 20, 30],
                [40, 50, 60]])
indices = np.array([[0, 1], [1, 2]])
print(extract_by_indices(arr, indices))

[20 60]


In [ ]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

#code >
import numpy as np
def filter_greater_than(arr, threshold):
    return arr[arr > threshold]

# example
arr = np.array([3, 6, 1, 9, 2])
print(filter_greater_than(arr, 4))

[6 9]


In [ ]:
# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

#code >
import numpy as np
def extract_3d_elements(arr, x_idx, y_idx, z_idx):
    return arr[x_idx, y_idx, z_idx]

# example
arr = np.arange(27).reshape((3, 3, 3))
x = np.array([0, 1, 2])
y = np.array([1, 0, 2])
z = np.array([2, 1, 0])
print(extract_3d_elements(arr, x, y, z))

[ 5 10 24]


In [ ]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

#code >
import numpy as np
def filter_two_conditions(arr):
    return arr[(arr > 3) & (arr < 8)]

# example
arr = np.array([1, 4, 6, 8, 10])
print(filter_two_conditions(arr))

[4 6]


In [ ]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

#code >
import numpy as np
def extract_with_row_col(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

# example
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
rows = np.array([0, 1, 2])
cols = np.array([2, 1, 0])
print(extract_with_row_col(arr, rows, cols))

[30 50 70]


In [ ]:
# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

#code >
import numpy as np
def add_scalar(arr):
    return arr + 5

# example
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(add_scalar(arr))

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

#code >
import numpy as np
def broadcast_multiply(arr1, arr2):
    return arr1.T * arr2

# example
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[1, 1, 1, 1],
                 [2, 2, 2, 2],
                 [3, 3, 3, 3]])
print(broadcast_multiply(arr1, arr2))

[[1 1 1 1]
 [4 4 4 4]
 [9 9 9 9]]


In [ ]:
# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

#code >
import numpy as np
def add_1d_to_2d(arr1, arr2):
    return arr2 + arr1.T

# example
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])
print(add_1d_to_2d(arr1, arr2))

[[ 11  21  31]
 [ 42  52  62]
 [ 73  83  93]
 [104 114 124]]


In [ ]:
# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

#code >
import numpy as np
def add_2d_broadcast(arr1, arr2):
    return arr1 + arr2

# example
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[10, 20, 30]])
print(add_2d_broadcast(arr1, arr2))

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

#code >
import numpy as np
def broadcast_multiply_incompatible(arr1, arr2):
    try:
        return arr1 * arr2
    except ValueError as e:
        return str(e)

# example
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[1, 2], [3, 4]])
print(broadcast_multiply_incompatible(arr1, arr2))

operands could not be broadcast together with shapes (2,3) (2,2) 


In [ ]:
# 41. Calculate column-wise mean for the given array:
# arr = np.array([[1, 2, 3], [4, 5, 6]])

#code >
import numpy as np
def column_mean(arr):
    return np.mean(arr, axis=0)

# example
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(column_mean(arr))

[2.5 3.5 4.5]


In [ ]:
# 42. Find maximum value in each row of the given array:
# arr = np.array([[1, 2, 3], [4, 5, 6]])

#code >
import numpy as np
def row_max(arr):
    return np.max(arr, axis=1)

# example
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(row_max(arr))

[3 6]


In [ ]:
# 43. For the given array, find indices of maximum value in each column.
# arr = np.array([[1, 2, 3], [4, 5, 6]])

#code >
import numpy as np
def max_indices_column(arr):
    return np.argmax(arr, axis=0)

# example
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(max_indices_column(arr))

[1 1 1]


In [ ]:
# 44. For the given array, apply custom function to calculate moving sum along rows.
# arr = np.array([[1, 2, 3], [4, 5, 6]])

#code >
import numpy as np
def moving_sum(arr, window=2):
    return np.array([np.convolve(row, np.ones(window, dtype=int), 'valid') for row in arr])

# example
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(moving_sum(arr))

[[ 3  5]
 [ 9 11]]


In [ ]:
# 45. In the given array, check if all elements in each column are even.
# arr = np.array([[1, 2, 3], [4, 5, 6]])

#code >
import numpy as np
def all_even_columns(arr):
    return np.all(arr % 2 == 0, axis=0)

# example
arr = np.array([[2, 4, 6], [3, 5, 7]])
print(all_even_columns(arr))

[False False False]


In [ ]:
# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
# original_array = np.array([1, 2, 3, 4, 5, 6])

#code >
import numpy as np
def reshape_array(arr, m, n):
    return arr.reshape((m, n))

#example >
original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_matrix = reshape_array(original_array, 2, 3)
print(reshaped_matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 47. Create a function that takes a matrix as input and returns the flattened array.
# input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

#code >
def flatten_matrix(matrix):
    return matrix.flatten()

# example
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(flatten_matrix(matrix))

[1 2 3 4 5 6]


In [ ]:
# 48. Write a function that concatenates two given arrays along a specified axis.
# array1 = np.array([[1, 2], [3, 4]])
# array2 = np.array([[5, 6], [7, 8]])

#code >
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

# example
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
print(concatenate_arrays(array1, array2, axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.
# original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#code >
def split_array(arr, sections, axis=0):
    return np.array_split(arr, sections, axis=axis)

#example >
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Split into 3 parts along axis=0 (rows)
split_result = split_array(original_array, 3, axis=0)
print(split_result)


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [ ]:
# 50. Write a function that inserts and then deletes elements from a given array at specified indices.
# original_array = np.array([1, 2, 3, 4, 5])
# indices_to_insert = [2, 4]
# values_to_insert = [10, 11]
# indices_to_delete = [1, 3]

#code >
def insert_and_delete(arr, ins_indices, ins_values, del_indices):
    arr = np.insert(arr, ins_indices, ins_values)
    arr = np.delete(arr, del_indices)
    return arr

# example
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
print(insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete))

[ 1 10  4 11  5]


In [26]:
# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

#code >
arr1 = np.random.randint(1, 100, 10)
arr2 = np.arange(1, 11)
print(arr1 + arr2)

[52 78 35 65 64 86 69 64 77 92]


In [27]:
# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

#code >
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
print(arr1 - arr2)

[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [28]:
# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

#code >
arr1 = np.random.randint(1, 10, 5)
arr2 = np.arange(1, 6)
print(arr1 * arr2)

[ 7 12 24 36 15]


In [29]:
# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

#code >
arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)
print(arr1 / arr2)

[2. 2. 2. 2. 2.]


In [30]:
# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

#code >
arr1 = np.arange(1, 6)
arr2 = arr1[::-1]
print(arr1 ** arr2)

[ 1 16 27 16  5]


In [31]:
# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
# arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello']

#code >
def count_substring(arr, substr):
    return np.char.count(arr, substr)

# example
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
print(count_substring(arr, 'hello'))

[1 0 1 0 1]


In [ ]:
# 57. Write a function that extracts uppercase characters from a NumPy array of strings.
# arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

#code >
def extract_uppercase(arr):
    return np.array([''.join([c for c in word if c.isupper()]) for word in arr])

# example
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
print(extract_uppercase(arr))

['H' 'W' 'OAI' 'GPT']


In [ ]:
# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
# arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

#code >
def replace_substring(arr, old, new):
    return np.char.replace(arr, old, new)

# example
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(replace_substring(arr, 'apple', 'fruit'))

['fruit' 'banana' 'grape' 'pinefruit']


In [ ]:
# 59. Write a function that concatenates strings in a NumPy array element-wise.
# arr1 = np.array(['Hello', 'World'])
# arr2 = np.array(['Open', 'AI'])

#code >
def concat_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

# example
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
print(concat_strings(arr1, arr2))

['HelloOpen' 'WorldAI']


In [32]:
# 60. Write a function that finds the length of the longest string in a NumPy array.
# arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

#code >
def max_string_length(arr):
    return max(np.char.str_len(arr))

# example
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(max_string_length(arr))

9


In [33]:
# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

#code >
import numpy as np
data = np.random.randint(1, 1001, 100)
print('Mean:', np.mean(data))
print('Median:', np.median(data))
print('Variance:', np.var(data))
print('Standard Deviation:', np.std(data))

Mean: 513.72
Median: 535.0
Variance: 73773.28160000002
Standard Deviation: 271.61237379766044


In [34]:
# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

#code >
arr = np.random.randint(1, 101, 50)
print('25th Percentile:', np.percentile(arr, 25))
print('75th Percentile:', np.percentile(arr, 75))

25th Percentile: 29.0
75th Percentile: 78.75


In [35]:
# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

#code >
x = np.random.randint(1, 100, 20)
y = np.random.randint(1, 100, 20)
print(np.corrcoef(x, y))

[[1.         0.18902003]
 [0.18902003 1.        ]]


In [36]:
# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

#code >
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b))

[[19 22]
 [43 50]]


In [37]:
# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

#code >
arr = np.random.randint(10, 1001, 50)
print('10th Percentile:', np.percentile(arr, 10))
print('25th Percentile (Q1):', np.percentile(arr, 25))
print('50th Percentile (Median):', np.percentile(arr, 50))
print('75th Percentile (Q3):', np.percentile(arr, 75))
print('90th Percentile:', np.percentile(arr, 90))

10th Percentile: 89.10000000000001
25th Percentile (Q1): 224.25
50th Percentile (Median): 518.5
75th Percentile (Q3): 821.0
90th Percentile: 945.0


In [38]:
# 66. Create a NumPy array of integers and find the index of a specific element.

#code >
arr = np.array([10, 20, 30, 40, 50])
index = np.where(arr == 30)[0][0]
print('Index of 30:', index)

Index of 30: 2


In [39]:
# 67. Generate a random NumPy array and sort it in ascending order.

#code >
arr = np.random.randint(1, 100, 10)
print('Sorted array:', np.sort(arr))

Sorted array: [29 31 32 34 41 59 67 71 83 86]


In [40]:
# 68. Filter elements >20 in the given NumPy array.
# arr = np.array([12, 25, 6, 42, 8, 30])

#code >
arr = np.array([12, 25, 6, 42, 8, 30])
print(arr[arr > 20])

[25 42 30]


In [41]:
# 69. Filter elements which are divisible by 3 from a given NumPy array.
# arr = np.array([1, 5, 8, 12, 15])

#code >
arr = np.array([1, 5, 8, 12, 15])
print(arr[arr % 3 == 0])

[12 15]


In [42]:
# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
# arr = np.array([10, 20, 30, 40, 50])

#code >
arr = np.array([10, 20, 30, 40, 50])
print(arr[(arr >= 20) & (arr <= 40)])

[20 30 40]


In [43]:
# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
# arr = np.array([1, 2, 3])

#code >
arr = np.array([1, 2, 3])
print('Byte order:', arr.dtype.byteorder)

Byte order: =


In [44]:
# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
# arr = np.array([1, 2, 3], dtype=np.int32)

#code >
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(True)
print(arr)

[16777216 33554432 50331648]


In [ ]:
# 73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
# arr = np.array([1, 2, 3], dtype=np.int32)

#code >
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
swapped = arr.view(arr.dtype.newbyteorder())
print('Original array:', arr)
print('Swapped array:', swapped)
print('Original dtype:', arr.dtype)
print('Swapped dtype:', swapped.dtype)

#example >
print(swapped)

Original array: [1 2 3]
Swapped array: [16777216 33554432 50331648]
Original dtype: int32
Swapped dtype: >i4
[16777216 33554432 50331648]


In [ ]:
# 74. For the given NumPy array, swap its byte order conditionally based on system endianness using `newbyteorder()`.
# arr = np.array([1, 2, 3], dtype=np.int32)

#code >
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)

if arr.dtype.byteorder in ('=', '<'):
    swapped = arr.view(arr.dtype.newbyteorder('>'))
else:
    swapped = arr.view(arr.dtype.newbyteorder('<'))

#example >
print(swapped)

[16777216 33554432 50331648]


In [ ]:
# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
# arr = np.array([1, 2, 3], dtype=np.int32)

#code >
arr = np.array([1, 2, 3], dtype=np.int32)
needs_swap = arr.dtype.byteorder not in ('=', '|')
print(needs_swap)

False


In [ ]:
# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

#code >
arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 99
print("arr1:", arr1)
print("copy_arr:", copy_arr)

arr1: [ 1  2  3  4  5  6  7  8  9 10]
copy_arr: [99  2  3  4  5  6  7  8  9 10]


In [ ]:
# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

#code >
matrix = np.random.randint(0, 10, (3, 3))
view_slice = matrix[:2, :2]
view_slice[0, 0] = 100
print("matrix:\n", matrix)
print("view_slice:\n", view_slice)

matrix:
 [[100   6   1]
 [  0   6   5]
 [  5   0   7]]
view_slice:
 [[100   6]
 [  0   6]]


In [ ]:
# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

#code >
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[:2, :]
view_b += 5
print("array_a:\n", array_a)
print("view_b:\n", view_b)

array_a:
 [[ 6  7  8]
 [ 9 10 11]
 [ 7  8  9]
 [10 11 12]]
view_b:
 [[ 6  7  8]
 [ 9 10 11]]


In [ ]:
# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

#code >
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[0, 0] = 999
print("orig_array:\n", orig_array)
print("reshaped_view:\n", reshaped_view)

orig_array:
 [[999   2   3   4]
 [  5   6   7   8]]
reshaped_view:
 [[999   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [ ]:
# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

#code >
data = np.random.randint(0, 10, (3, 4))
data_copy = data[data > 5].copy()
data_copy[0] = 999
print("data:\n", data)
print("data_copy:\n", data_copy)

data:
 [[9 7 0 2]
 [9 2 0 7]
 [5 0 0 8]]
data_copy:
 [999   7   9   7   8]


In [ ]:
# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

#code >
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
add_result = A + B
sub_result = A - B
print("Addition:\n", add_result)
print("Subtraction:\n", sub_result)

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]


In [ ]:
# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

#code >
C = np.array([[1, 2], [3, 4], [5, 6]])
D = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])
result = np.matmul(C, D)
print("Matrix Multiplication:\n", result)

Matrix Multiplication:
 [[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [ ]:
# 83. Create a matrix `E` and find its transpose.

#code >
E = np.array([[1, 2, 3], [4, 5, 6]])
transpose_E = E.T
print("E:\n", E)
print("Transpose:\n", transpose_E)

E:
 [[1 2 3]
 [4 5 6]]
Transpose:
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
# 84. Generate a square matrix `F` and compute its determinant.

#code >
F = np.array([[6, 1], [4, 2]])
det = np.linalg.det(F)
print("Determinant:", det)

Determinant: 8.000000000000002


In [ ]:
# 85. Create a square matrix `G` and find its inverse.

#code >
G = np.array([[4, 7], [2, 6]])
inv_G = np.linalg.inv(G)
print("Inverse:\n", inv_G)

Inverse:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
